name: Update README with latest project

on:
  schedule:
    - cron: "30 * * * *"

  workflow_dispatch:

jobs:
  update-project:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Check the latest project from Github events
      run: python ./.github/workflows/update_project.py

    - name: Commit the new README
      uses: test-room-7/action-update-file@v1
      with:
          file-path: README.md
          commit-msg: Update README.md with the latest project
          github-token: ${{ secrets.GITHUB_TOKEN }}
